import {
  ProfileData,
  ProjectData,
  ExperienceData,
  EducationData,
  SkillCategoryData,
  CertificationData,
  LifeUpdateData,
} from "@/types";

export const DEFAULT_PROFILE: ProfileData = {
  name: "Dagm Ayalew",
  title: "Senior Mobile App Developer",
  tagline: "I build production-grade mobile applications with React Native, TypeScript, Flutter, and scalable mobile architecture.",
  bio: "Senior Mobile App Developer specializing in React Native, TypeScript, and mobile architecture. Experienced in delivering banking super apps, agent banking solutions, and high-traffic e-commerce platforms.",
  aboutMe: "I am a Senior Mobile App Developer and Full-Stack Engineer based in Addis Ababa, Ethiopia. I specialize in building robust, production-ready mobile applications using React Native, TypeScript, and modern mobile state and caching architectures.\n\nMy experience includes mobile contributions to banking super apps serving over 1M+ downloads (Dashen Super App), developing agent banking platforms with biometric authentication and secure session handling (Ethio Post Agent Banking), and engineering e-commerce applications with live geolocation routing (Order Ethiopia).\n\nI focus on clean architecture, maintainable codebases, reliable API contracts, and delivering responsive mobile user experiences.",
  email: "dagmayalew489@gmail.com",
  phone: "+251988280976",
  location: "Addis Ababa, Ethiopia",
  avatarUrl: "https://avatars.githubusercontent.com/dagmayalew",
  resumeUrl: "/cv",
  githubUrl: "https://github.com/dagmayalew",
  linkedinUrl: "https://linkedin.com/in/dagmay-ayalew",
  twitterUrl: "https://twitter.com/dagmayalew",
  playStoreDevUrl: "https://play.google.com",
  appStoreDevUrl: "https://apps.apple.com",
  isOpenToWork: true,
  statusMessage: "Senior Mobile App Developer at Eaglelion System Technology | Building React Native & FinTech apps",
  statusUpdatedAt: new Date().toISOString(),
  themeSettings: {
    accentColor: "emerald",
    preset: "emerald",
    customPrimaryColor: "#10b981",
    customSecondaryColor: "#06b6d4",
    mode: "dark",
    glassmorphism: true,
    glassIntensity: "low",
    borderRadius: "lg",
    fontFamily: "sans",
    backgroundPattern: "clean",
    glowIntensity: "subtle",
    showPhoneMockup: true,
    showLiveStatusBadge: true,
    enableAnimations: true,
    heroHeadlineStyle: "solid",
    sectionVisibility: {
      showHero: true,
      showProjects: true,
      showExperience: true,
      showSkills: true,
      showContact: true,
    },
    sectionContent: {
      heroHeadline: "Senior Mobile App Developer",
      heroIntro: "Specialized in React Native, TypeScript, and Mobile Architecture, with production experience across financial super apps, agency banking, and e-commerce platforms. Also proficient in Flutter and Full-Stack development.",
      heroTechPills: ["React Native", "TypeScript", "Flutter", "Full-Stack (Next.js & Node.js)"],
      projectsTitle: "Featured Mobile Projects",
      projectsSubtitle: "Production React Native and mobile applications built for scale, performance, and real user workflows.",
      experienceTitle: "Work Experience",
      experienceSubtitle: "Track record of shipping production mobile applications and leading feature delivery.",
      skillsTitle: "Technologies & Tools",
      skillsSubtitle: "Focused on production React Native mobile architectures, with end-to-end full-stack capabilities.",
      contactTitle: "Get In Touch",
      contactSubtitle: "Interested in discussing a mobile engineering project, senior role, or technical collaboration? Send a message below or reach out directly.",
    },
    phoneMockupSettings: {
      defaultApp: "dashen",
      frameStyle: "titanium-dark",
      dynamicIslandText: "Dashen Super App",
      bankingBalance: "248,500.00",
      bankingCurrency: "ETB",
      bankingCardholder: "Dagm Ayalew",
      bankingKycBadge: "Fayda Verified",
      deliveryRoute: "Bole Medhanialem → Kazanchis",
      deliveryEta: "ETA 8 MIN",
      cryptoAlgorithm: "Biometric & Token Auth",
    },
  },
};

export const DEFAULT_PROJECTS: ProjectData[] = [
  {
    id: "proj-1",
    title: "Dashen Super App",
    slug: "dashen-super-app",
    role: "Mobile Application Developer",
    summary: "A mobile banking and super app for Dashen Bank Ethiopia featuring financial transactions, e-commerce mini-applications, and Fayda KYC onboarding with 1M+ downloads.",
    description: "Developed and integrated key modules for the Dashen Bank Super App at Eaglelion System Technology. Contributed to core transaction flows, bill settlements, e-commerce mini-app integration, Fayda national identity KYC onboarding, and financial REST API integrations with Zustand state management.",
    platform: "React Native / FinTech",
    appStoreUrl: "https://apps.apple.com",
    playStoreUrl: "https://play.google.com",
    githubUrl: "https://github.com/dagmayalew",
    liveDemoUrl: "https://www.dashenbanksc.com",
    thumbnail: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    ],
    featured: true,
    techStack: ["React Native", "TypeScript", "Zustand", "REST APIs", "Fayda KYC", "Offline Storage"],
    keyMetrics: {
      downloads: "1M+ Downloads (Google Play)",
      rating: "Eaglelion System Tech",
      activeUsers: "Core Banking",
    },
    caseStudy: {
      overview: "Dashen Bank Super App is a digital financial platform in Ethiopia, providing users with mobile banking services, utility payments, QR merchant transactions, and digital mini-applications.",
      role: "Mobile Application Developer at Eaglelion System Technology, responsible for implementing user transaction flows, mini-application views, Fayda KYC onboarding, and REST API integrations.",
      challenge: "Handling network instability during payment submissions to prevent redundant requests, while maintaining a smooth and responsive interface across diverse Android and iOS devices.",
      solution: "Implemented predictable state management with Zustand, created robust API interceptors with automatic token refresh, and designed clear transactional UI states with explicit user feedback.",
      architecture: [
        "Modular React Native & TypeScript client structure organized by feature domains",
        "Zustand state store for predictable client state management and cache persistence",
        "Fayda national identity KYC verification and onboarding workflow",
        "Defensive API request handling and error boundaries",
        "Optimized list rendering for transaction histories and account statements",
      ],
      results: [
        "Shipped key modules contributing to an app with 1M+ downloads on Google Play",
        "Improved transaction submission reliability under intermittent network conditions",
        "Delivered responsive, native-feeling UI interactions across multiple device tiers",
      ],
      takeaways: [
        "Financial mobile applications require defensive state architectures and clear user feedback on network failures.",
        "Modular domain separation significantly improves maintainability when multiple developers collaborate on feature-rich super apps.",
      ],
    },
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "proj-2",
    title: "Ethio Post Agent Banking",
    slug: "ethiopost-agent-banking",
    role: "Mobile Application Developer",
    summary: "Agency banking mobile application for Ethiopian Postal Service agents, featuring agent authentication, cash-in/cash-out transaction flows, and encrypted session storage.",
    description: "Built the mobile client application for postal agency banking operations at Eaglelion System Technology. Implemented the complete user interface from scratch, biometric authentication (Face ID & Fingerprint), OTP verification, PIN setup, secure token storage, cash transaction flows, and session error handling.",
    platform: "React Native / Agent Banking",
    appStoreUrl: "https://apps.apple.com",
    playStoreUrl: "https://play.google.com",
    githubUrl: "https://github.com/dagmayalew",
    liveDemoUrl: "https://www.ethiopost.et",
    thumbnail: "https://images.unsplash.com/photo-1526367790999-0150786686a2?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
    ],
    featured: true,
    techStack: ["React Native", "TypeScript", "Biometric Auth", "Secure Storage", "TanStack Query", "OTP Verification"],
    keyMetrics: {
      downloads: "Postal Agent Network",
      rating: "Eaglelion System Tech",
      activeUsers: "Agent Banking",
    },
    caseStudy: {
      overview: "Ethio Post Agent Banking provides postal agents across Ethiopia with a mobile terminal interface to perform cash deposits, cash withdrawals, utility payments, and transfers for postal customers.",
      role: "Mobile Application Developer at Eaglelion System Technology who built the complete mobile UI, implemented biometric and PIN authentication, and integrated agent banking transaction workflows.",
      challenge: "Ensuring secure credential management on field agent devices while maintaining fast, straightforward transaction workflows for high-frequency daily operations.",
      solution: "Implemented biometric authentication (Face ID / Fingerprint) paired with encrypted local storage for session tokens, clean form validation for transaction amounts, and automatic session cleanup on logout.",
      architecture: [
        "Complete mobile application UI built from scratch with reusable component design system",
        "Biometric authentication pipeline with fallback PIN verification",
        "Encrypted local storage for authentication tokens and agent session state",
        "TanStack Query for efficient server state synchronization and cache management",
        "Structured error handling and session timeout interceptors",
      ],
      results: [
        "Successfully deployed across postal agent branches nationwide",
        "Delivered a clean, straightforward workflow for daily agent cash-in and cash-out tasks",
        "Maintained consistent session security across shared agency mobile devices",
      ],
      takeaways: [
        "Agent-facing operational tools benefit greatly from minimal, high-contrast layouts and explicit form validations.",
        "Combining biometric login with encrypted storage streamlines repeated agent authentication.",
      ],
    },
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "proj-3",
    title: "Order Ethiopia",
    slug: "order-ethiopia",
    role: "React Native Mobile Developer",
    summary: "Cross-platform e-commerce and delivery mobile app featuring user onboarding with OTP authentication, Gebeta Maps GPS location routing, and merchant catalog browsing.",
    description: "Developed core mobile features for the Order Ethiopia e-commerce and food delivery platform. Implemented authentication (registration, login, OTP verification, password reset), dynamic home feeds, merchant store listings, product detail views with variant selection, cart management, and Gebeta Maps live GPS location integration.",
    platform: "React Native / E-Commerce",
    appStoreUrl: "https://apps.apple.com",
    playStoreUrl: "https://play.google.com",
    githubUrl: "https://github.com/dagmayalew",
    liveDemoUrl: "https://orderethiopia.com",
    thumbnail: "https://images.unsplash.com/photo-1556742044-3c52d6e88c62?auto=format&fit=crop&w=1200&q=80",
    screenshots: [
      "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
    ],
    featured: true,
    techStack: ["React Native", "TypeScript", "Gebeta Maps", "OTP Verification", "Zustand", "TanStack Query", "REST APIs"],
    keyMetrics: {
      downloads: "E-Commerce & Food Delivery",
      rating: "Addis Ababa, ET",
      activeUsers: "Multi-Merchant",
    },
    caseStudy: {
      overview: "Order Ethiopia is a multi-merchant mobile delivery platform connecting consumers in Addis Ababa with local restaurants, supermarkets, and specialty retail shops.",
      role: "React Native Mobile Developer responsible for developing the customer onboarding flows, SMS OTP verification, store and merchant discovery feeds, product catalogs, and live GPS map tracking.",
      challenge: "Building a responsive catalog browsing experience with smooth product image loading, combined with frictionless SMS OTP verification for Ethiopian mobile numbers.",
      solution: "Utilized efficient list virtualization, optimized image caching, implemented automatic SMS OTP handling with resend countdown timers, and integrated the Gebeta Maps SDK for delivery address selection.",
      architecture: [
        "Complete customer authentication workflow: Login, Register, SMS OTP Verification, Password Recovery",
        "Home discovery feed featuring categorized merchant stores, promotional carousels, and search filters",
        "Product detail views with item variants, special instructions, and real-time cart synchronization",
        "Live location mapping using the Gebeta Maps mobile SDK",
      ],
      results: [
        "Delivered a smooth customer onboarding experience with reliable phone-based OTP verification",
        "Maintained fast, responsive list scrolling across extensive merchant catalogs",
        "Created a seamless checkout flow from cart creation to order placement",
      ],
      takeaways: [
        "Local phone OTP authentication requires clear retry states and countdown timers to handle cellular SMS delays.",
        "Careful memory management in product list views is essential for smooth e-commerce browsing on mid-range devices.",
      ],
    },
    order: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: "proj-4",
    title: "BetFind",
    slug: "betfind",
    role: "Founder / Developer",
    summary: "A local discovery platform designed to help people find home supplies, hardware materials, furniture, and maintenance services nearby.",
    description: "Designed and developed BetFind as an end-to-end MVP. Built the mobile application using React Native and TypeScript, paired with a Go REST API and PostgreSQL database for localized category search, merchant listings, and direct communication channels.",
    platform: "React Native / Full-Stack (Go & PostgreSQL)",
    appStoreUrl: null,
    playStoreUrl: null,
    githubUrl: "https://github.com/dagmayalew",
    liveDemoUrl: null,
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
    screenshots: [],
    featured: true,
    techStack: ["React Native", "TypeScript", "Go (Golang)", "PostgreSQL", "REST APIs"],
    keyMetrics: {
      downloads: "Founder Project / MVP",
      rating: "Full-Stack System",
      activeUsers: "Local Discovery",
    },
    caseStudy: {
      overview: "BetFind is a local discovery application designed to help homeowners, builders, and renters easily locate local home improvement supplies, building materials, and verified maintenance tradespeople.",
      role: "Founder & Full-Stack Developer responsible for product concept, React Native mobile app development, backend REST API development in Go, and PostgreSQL schema design.",
      challenge: "Structuring fragmented local merchant inventories into a simple, searchable mobile interface without complex onboarding overhead for non-technical shop owners.",
      solution: "Engineered a lightweight Go backend API with PostgreSQL query indexing, paired with a clean React Native mobile app featuring category browsing, search filters, and direct merchant contact buttons.",
      architecture: [
        "React Native mobile frontend with clean component architecture and local search caching",
        "Go REST API backend structured for fast endpoint delivery",
        "PostgreSQL database schema with indexing for category and keyword search",
        "Direct contact channels enabling users to call or message merchants directly",
      ],
      results: [
        "Built a working MVP demonstrating full-stack product development from concept to code",
        "Delivered fast response times across backend endpoints and mobile views",
        "Validated localized merchant discovery workflows with practical UX patterns",
      ],
      takeaways: [
        "Focusing on the core user problem first leads to simpler, more dependable software.",
        "Pairing React Native with a typed Go backend provides high developer productivity and runtime efficiency.",
      ],
    },
    order: 4,
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_EXPERIENCES: ExperienceData[] = [
  {
    id: "exp-1",
    company: "Eaglelion System Technology",
    role: "Senior Mobile App Developer",
    location: "Addis Ababa, Ethiopia",
    startDate: "Feb 2026",
    endDate: "Present",
    isCurrent: true,
    description: "Senior mobile engineer driving production React Native development, fintech banking modules, agency banking applications, and scalable mobile architecture.",
    achievements: [
      "Architected and shipped production mobile features using React Native and TypeScript for financial applications.",
      "Implemented biometric authentication (Face ID & Fingerprint) and encrypted token storage for secure session handling.",
      "Integrated core financial REST APIs with robust error boundaries and state synchronization.",
      "Collaborated with cross-functional design and backend teams to deliver maintainable, component-driven mobile UI flows.",
    ],
    techStack: ["React Native", "TypeScript", "Zustand", "Biometrics", "Financial APIs", "REST APIs", "TanStack Query"],
    type: "FULL_TIME",
    order: 1,
  },
  {
    id: "exp-2",
    company: "TBC Technologies",
    role: "Full-Stack and Mobile Developer / Tech Lead",
    location: "Addis Ababa, Ethiopia",
    startDate: "Mar 2024",
    endDate: "Feb 2026",
    isCurrent: false,
    description: "Led mobile and web feature development, resolved production stability issues, integrated resilient REST APIs, and guided technical deliverables.",
    achievements: [
      "Developed responsive mobile and web features across client projects using React Native, React, and Next.js.",
      "Diagnosed and resolved critical production crash issues and implemented React error boundaries to improve application stability.",
      "Integrated REST APIs with structured state management and defensive error handling.",
      "Mentored junior developers, conducted code reviews, and contributed to technical architecture discussions.",
    ],
    techStack: ["React Native", "React", "Next.js", "TypeScript", "REST APIs", "Error Boundaries", "Git"],
    type: "FULL_TIME",
    order: 2,
  },
];

export const DEFAULT_EDUCATION: EducationData[] = [
  {
    id: "edu-1",
    institution: "Unity University, Addis Ababa (Gerji Campus)",
    degree: "Bachelor of Science",
    fieldOfStudy: "Computer Science",
    startDate: "2021",
    endDate: "2025",
    isCurrent: false,
    grade: "Graduated 2025",
    activities: [
      "Focused on Software Engineering, Mobile Architectures, Data Structures, and Database Systems",
      "Active participant in developer workshops and technical projects",
    ],
    order: 1,
  },
];

export const DEFAULT_SKILL_CATEGORIES: SkillCategoryData[] = [
  {
    id: "cat-1",
    name: "Mobile Development",
    order: 1,
    skills: [
      { id: "sk-1", name: "React Native", proficiency: 96, yearsOfExp: 3, iconName: "Smartphone", featured: true, categoryId: "cat-1", order: 1 },
      { id: "sk-2", name: "TypeScript", proficiency: 94, yearsOfExp: 3, iconName: "Terminal", featured: true, categoryId: "cat-1", order: 2 },
      { id: "sk-3", name: "Mobile Architecture", proficiency: 92, yearsOfExp: 3, iconName: "Layers", featured: true, categoryId: "cat-1", order: 3 },
      { id: "sk-4", name: "Flutter & Dart", proficiency: 88, yearsOfExp: 2, iconName: "Smartphone", featured: true, categoryId: "cat-1", order: 4 },
      { id: "sk-5", name: "State Management (Zustand / Redux)", proficiency: 90, yearsOfExp: 3, iconName: "Workflow", featured: true, categoryId: "cat-1", order: 5 },
      { id: "sk-6", name: "Biometric & Token Auth", proficiency: 90, yearsOfExp: 3, iconName: "Smartphone", featured: true, categoryId: "cat-1", order: 6 },
    ],
  },
  {
    id: "cat-2",
    name: "Frontend Development",
    order: 2,
    skills: [
      { id: "sk-7", name: "Next.js", proficiency: 92, yearsOfExp: 2, iconName: "Server", featured: true, categoryId: "cat-2", order: 1 },
      { id: "sk-8", name: "React", proficiency: 95, yearsOfExp: 3, iconName: "Globe", featured: true, categoryId: "cat-2", order: 2 },
      { id: "sk-9", name: "Tailwind CSS", proficiency: 92, yearsOfExp: 3, iconName: "Layers", featured: true, categoryId: "cat-2", order: 3 },
      { id: "sk-10", name: "Responsive UI Design", proficiency: 90, yearsOfExp: 3, iconName: "Globe", featured: false, categoryId: "cat-2", order: 4 },
    ],
  },
  {
    id: "cat-3",
    name: "Backend & APIs",
    order: 3,
    skills: [
      { id: "sk-11", name: "Node.js", proficiency: 90, yearsOfExp: 3, iconName: "Server", featured: true, categoryId: "cat-3", order: 1 },
      { id: "sk-12", name: "Express.js", proficiency: 88, yearsOfExp: 3, iconName: "Server", featured: true, categoryId: "cat-3", order: 2 },
      { id: "sk-13", name: "REST APIs & JSON", proficiency: 95, yearsOfExp: 3, iconName: "Workflow", featured: true, categoryId: "cat-3", order: 3 },
      { id: "sk-14", name: "Go (Golang)", proficiency: 82, yearsOfExp: 2, iconName: "Terminal", featured: false, categoryId: "cat-3", order: 4 },
    ],
  },
  {
    id: "cat-4",
    name: "Database & Cloud",
    order: 4,
    skills: [
      { id: "sk-15", name: "PostgreSQL", proficiency: 92, yearsOfExp: 3, iconName: "Database", featured: true, categoryId: "cat-4", order: 1 },
      { id: "sk-16", name: "Prisma ORM", proficiency: 90, yearsOfExp: 2, iconName: "Database", featured: true, categoryId: "cat-4", order: 2 },
      { id: "sk-17", name: "Supabase", proficiency: 88, yearsOfExp: 2, iconName: "Database", featured: true, categoryId: "cat-4", order: 3 },
      { id: "sk-18", name: "Firebase", proficiency: 88, yearsOfExp: 2, iconName: "Flame", featured: false, categoryId: "cat-4", order: 4 },
    ],
  },
  {
    id: "cat-5",
    name: "Tools & Workflow",
    order: 5,
    skills: [
      { id: "sk-19", name: "Git & GitHub", proficiency: 95, yearsOfExp: 3, iconName: "Terminal", featured: true, categoryId: "cat-5", order: 1 },
      { id: "sk-20", name: "Postman", proficiency: 92, yearsOfExp: 3, iconName: "Terminal", featured: true, categoryId: "cat-5", order: 2 },
      { id: "sk-21", name: "EAS (Expo Application Services)", proficiency: 88, yearsOfExp: 2, iconName: "Smartphone", featured: true, categoryId: "cat-5", order: 3 },
      { id: "sk-22", name: "Android Studio & Xcode basics", proficiency: 85, yearsOfExp: 2, iconName: "Smartphone", featured: false, categoryId: "cat-5", order: 4 },
    ],
  },
];

export const DEFAULT_CERTIFICATIONS: CertificationData[] = [
  {
    id: "cert-1",
    title: "Meta Certified React Native Specialist",
    issuer: "Meta",
    issueDate: "2024",
    credentialId: "META-RN-2024",
    order: 1,
  },
];

export const DEFAULT_LIFE_UPDATES: LifeUpdateData[] = [
  {
    id: "up-1",
    content: "Building production React Native modules and financial transaction flows at Eaglelion System Technology.",
    tag: "BUILDING",
    emoji: "",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "up-2",
    content: "Shipped Dashen Super App transaction flows and merchant integrations with over 1M+ downloads on Google Play.",
    tag: "MILESTONE",
    emoji: "",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "up-3",
    content: "Refined Order Ethiopia e-commerce UI with OTP verification and merchant catalog browsing.",
    tag: "LEARNING",
    emoji: "",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
];
